#nom du workflow
name: First workflow 
 #specifier le trigger qui va declencher les evenements
 #workflow_dispatch signifie que nous allons nous meme lancer le declenchement
on: workflow_dispatch

#les taches a faires
jobs:
  first-job: # nom de la premiere tache
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello world"
      - name: print goodbye
        run: echo "Done-bye!"
